name: Build for Mac
on: [workflow_dispatch]

jobs:
    build-mac:
        name: Build for Mac
        runs-on: macos-14
        strategy:
          fail-fast: false
          matrix:
              target: [iOS, tvOS, visionOS, '']

        steps:
          - uses: actions/checkout@v4
            with:
                submodules: recursive
          - name: Setup Xcode version
            uses: maxim-lobanov/setup-xcode@v1.6.0
            with:
                xcode-version: "16.1"

          - name: Set project env vars
            run: |
              ICON_PATH=$(python3 -c "import json; print(json.load(open('assets/info.json'))['icon-path'])")
              PROJECT=$(python3 -c "import json; print(json.load(open('assets/info.json'))['project'])")
              echo "ICON_PATH=$ICON_PATH" >> $GITHUB_ENV
              echo "PROJECT=$PROJECT" >> $GITHUB_ENV

          - name: Configure
            run: cmake -G "Xcode" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -S . -B build
          - name: Build
            run: cmake --build build --target install --config Release
          - name: Ad-Hoc Codesign
            run: codesign -s - -f "./build/release/${{ env.PROJECT }}.app" --deep
          - name: Create DMG
            run: | 
                cd build
                hdiutil create -size 2g -srcfolder release -volname sdl_min_apple_${{ matrix.target }} sdl_min_apple_${{ matrix.target }}.dmg
          - name: Upload Build
            uses: actions/upload-artifact@v4
            with: 
                name: ${{ env.PROJECT }}-apple-${{ matrix.target }}
                path: build/*.dmg
